/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Parse a single Ableton Live Set file and return its structure as JSON.
 * Useful for displaying track info without diffing.
 */
export declare function parseAls(filepath: string): string

/**
 * Parse and diff two Ableton Live Set files by file path.
 *
 * Returns a JSON string containing the full DiffReport:
 * `{ stats, changes, project }`
 */
export declare function parseXml(currentFilepath: string, oldAlsPath: string): string

/**
 * Parse and diff two Ableton Live Set files from in-memory buffers.
 *
 * Accepts gzip-compressed or plain XML buffers (auto-detected).
 * This enables diffing git blobs directly without writing to disk.
 *
 * Returns a JSON string containing the full DiffReport.
 */
export declare function parseXmlFromBuffer(currentBuf: Buffer, oldBuf: Buffer): string
