/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Diff a previously-serialized Project snapshot against the current ALS file.
 *
 * `snapshot_json` — the contents of `.soundhaus/{session}/snapshot.json` from the last commit.
 * `current_als_path` — absolute path to the current .als file on disk.
 *
 * Returns the same JSON DiffReport shape as `parseXmlFromBuffer`, enabling the
 * `get-changes` IPC handler to skip re-parsing the HEAD ALS blob entirely.
 */
export declare function diffFromSnapshot(snapshotJson: string, currentAlsPath: string): Promise<string>

/**
 * Generate a human-readable git commit message from a serialized DiffReport JSON string.
 * Mirrors the `buildCommitMessage` logic previously in `main.ts`.
 */
export declare function generateCommitMessage(diffReportJson: string): Promise<string>

/**
 * Parse a single Ableton Live Set file and serialize it as a Project JSON snapshot.
 * Primary snapshot serialization path: result is written to `.soundhaus/{session}/snapshot.json`.
 */
export declare function parseAls(filepath: string): Promise<string>

/**
 * Parse and diff two Ableton Live Set files by file path.
 *
 * Returns a JSON string containing the full DiffReport:
 * `{ stats, changes, project }`
 */
export declare function parseXml(currentFilepath: string, oldAlsPath: string): Promise<string>

/**
 * Parse and diff two Ableton Live Set files from in-memory buffers.
 *
 * Accepts gzip-compressed or plain XML buffers (auto-detected).
 * This enables diffing git blobs directly without writing to disk.
 *
 * Returns a JSON string containing the full DiffReport.
 */
export declare function parseXmlFromBuffer(currentBuf: Buffer, oldBuf: Buffer): Promise<string>
